config/routes.rb
Propeixo::Application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks do
      resources :work_intervals
    end
  end

  root :to => 'pages#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name, :planned_duration, :start

  validates :name, :presence => true

  belongs_to :user
  has_many :tasks, :dependent => :destroy

  def time_spent
    seconds = self.tasks.sum(&:time_spent)
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :name, :planned_duration

  validates :name, :presence => true

  belongs_to :project
  has_many :work_intervals, :dependent => :destroy

  # Checks if the current task has any active work interval
  def has_wip?
    return true if self.work_intervals.where(:end_date => nil).any?
    return false
  end

  # Return time spend in task (in seconds)
  def time_spent
    if self.work_intervals.empty?
      return 0
    else
      seconds = self.work_intervals
      .map {|i| (i.end_date || Time.now).to_time - i.start_date.to_time }
      .reduce(:+)
    end
  end

  def active_work_interval 
    self.work_intervals.where(end_date: nil).last
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  #
  
  has_many :projects
end

app/models/work_interval.rb
class WorkInterval < ActiveRecord::Base
  attr_accessible :end_date, :start_date

  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def permission_denied
    flash[:notice] = 'Sorry, you are not authorized to access that page.'
    redirect_to root_url and return
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html, :js

  before_filter :authenticate_user!

  def index
    @projects = current_user.projects

    respond_with @projects
  end

  def new
    @project = Project.new

    respond_with @project
  end

  def create
    @user = current_user
    @project = @user.projects.build(params[:project])

    if @project.save
      flash[:success] = 'Project has been created successfully'
    end
    respond_with @project
  end

  def edit
    @project = Project.find(params[:id])
    return permission_denied if !current_user.projects.include?(@project)

    respond_with @project
  end

  def update
    @project = Project.find(params[:id])
    return permission_denied if !current_user.projects.include?(@project)

    if @project.update_attributes(params[:project])
      flash[:success] = 'Project has been edited successfully'
    end

    respond_with @project
  end

  def destroy
    @project = Project.find(params[:id])
    return permission_denied if !current_user.projects.include?(@project)

    @project.destroy
    flash[:success] = 'project has been destroyed succesfully'

    respond_with @project
  end

  def show
    @project = Project.find(params[:id])
    return permission_denied if !current_user.projects.include?(@project)

    @tasks = @project.tasks

    respond_with @project
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :js

  before_filter :authenticate_user!

  def index
    @project = Project.find(params[:project_id])
    @tasks = current_user.projects.find(params[:project_id]).tasks

    respond_with @tasks
  end

  def new
    @project = Project.find(params[:project_id])
    @task = Task.new

    respond_with @task
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build(params[:task])

    if @task.save
      flash[:success] = 'Task has been created successfully'
    end

    redirect_to project_path(@project)
  end

  def edit
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    return permission_denied if !current_user.projects.include?(@project)

    respond_with [@project, @task]
  end

  def update
    @project = Project.find(params[:project_id])
    return permission_denied if !current_user.projects.include?(@project)
    
    @task = @project.tasks.find(params[:id])

    if @task.update_attributes(params[:task])
      flash[:success] = 'Task has been edited successfully'
    end

    redirect_to :back
  end

  def destroy
    @project = Project.find(params[:project_id])
    return permission_denied if !current_user.projects.include?(@project)

    @task = @project.tasks.find(params[:id])

    @task.destroy
    flash[:success] = 'Task has been destroyed succesfully'

    redirect_to :back
  end

  def show
    @project = Project.find(params[:project_id])
    return permission_denied if !current_user.projects.include?(@project)

    @task = @project.tasks.find(params[:id])
    @work_interval = @task.work_intervals.where(end_date: nil).last

    respond_with [@project, @task]
  end
end

app/controllers/work_intervals_controller.rb
class WorkIntervalsController < ApplicationController
  respond_to :html, :js

  before_filter :authenticate_user!

  def create
    @project = Project.find(params[:project_id])
    return permission_denied if !current_user.projects.include?(@project)

    @task = @project.tasks.find(params[:task_id])
    @work_interval = @task.work_intervals.build(params[:work_interval])
    @work_interval.start_date = DateTime.now

    if @work_interval.save
      flash[:success] = 'Yes! You started working :)'
      redirect_to :back 
    end

  end

  def update
    @project = Project.find(params[:project_id])
    return permission_denied if !current_user.projects.include?(@project)
    
    @task = @project.tasks.find(params[:task_id])
    @work_interval = @task.work_intervals.find(params[:id])

    if @work_interval.update_attributes(:end_date => DateTime.now)
      flash[:success] = 'Alright, you stopped working!'
      redirect_to :back
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end
  end

  TimeInt = Struct.new :name, :secs
  INTERVALS = [ TimeInt[:days, 60*60*24], TimeInt[:hours, 60*60],
                  TimeInt[:minutes, 60], TimeInt[:seconds, 1] ]
  def time_with_adaptive_units(secs)
    ti = INTERVALS.find {|ti| secs >= ti.secs} || INTERVALS.last
    "#{(secs/ti.secs).round} #{ti.name}"
  end
end

app/views/layouts/_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="nav-collapse">
        <%= link_to "Propeixo", root_path, :class => 'brand' %>
        <ul class="nav">
          <% if user_signed_in? %>
            <li>
            <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
            </li>
          <% else %>
            <li>
            <%= link_to 'Login', new_user_session_path %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li>
            <%= link_to 'My Projects', projects_path %>
            </li>
            <li>
            <%= link_to 'Edit account', edit_user_registration_path %>
            </li>
          <% else %>
            <li>
            <%= link_to 'Sign up', new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Propeixo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Devise Rspec Cucumber" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/pages/index.html.erb
<h2> Manage your projects. Easily. </h2>
<% if user_signed_in? %>
  <%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited
          this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :planned_duration %><br />
    <%= f.number_field :planned_duration %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1> Projects </h1>
<% unless @projects.empty? %>
<table>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <td><strong><%= project.name %></strong></td>
      <td>
        <%= link_to 'Show', project, :class => 'btn'%>
        <%= link_to 'Edit', edit_project_path(project), :class => 'btn'%>
        <%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, :class => 'btn'%>
      </td>
    </tr>
  <% end %>
</table>
<% else %>
  <h2> It seems you don't have projects yet... </h2>
<% end %>

<br>
<%= link_to 'New Project', new_project_path, :class => 'btn btn-large'%>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render 'form' %>

app/views/projects/show.html.erb
<h1> Project: <%= @project.name %> </h1>

<p class="lead">
  <%= @project.description %>
</p>

<p>
  <b> Total Time Spent: </b> <%= time_with_adaptive_units(@project.time_spent) %> </b>
</p>


<div class="actions">
  <%= link_to 'Add Task to Project', new_project_task_path(@project), :class => 'btn btn-primary'%>
  <%= link_to 'Edit Project', edit_project_path(@project), :class => 'btn'%>
  <%= link_to 'Destroy Project', @project, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger' %>
</div>

<div class="task-container">

  <% if @tasks %> 
    <h1> List of Tasks </h1>
    <% @tasks.each do |task| %>
      <p>
        <b> Name: </b> <%= task.name %><br>
        <b> Time spent: </b> <%= time_with_adaptive_units(task.time_spent) %><br>
      </p>
      <div class="actions">
        <%= link_to 'Edit Task', edit_project_task_path(@project, task), :class => 'btn'%>
        <%= link_to 'Destroy Task', [@project, task], :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger' %>
        <% unless task.has_wip? %>
          <%= form_for [@project, task, task.work_intervals.build] do |f| %>
            <%= f.submit 'Start Working!', :class => 'btn btn-success' %>
          <% end %>
        <% else %>
          <%= form_for [@project, task, task.active_work_interval] do |f| %>
            <%= f.submit 'Stop Working!', :class => 'btn btn-danger' %>
          <% end %>
        <% end %>
      </div>
      <hr>
    <% end %>
  <% else %>
    <div> Uh, oh... No tasks yet... </div>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited
          this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :planned_duration %><br />
    <%= f.number_field :planned_duration %>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>
<%= render 'form' %>

app/views/tasks/index.html.erb
<table>
  <tr>
    <th>Name</th>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= link_to 'Show', project_task_path(@project, task) %></td>
      <td><%= link_to 'Edit', edit_project_task_path(@project, task) %></td>
      <td><%= link_to 'Destroy', project_task_path(@project, task), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>

</table>

app/views/tasks/new.html.erb
<h2>New Task</h2>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1> <%= @task.name %> </h1> 

<div class="task_description">
  <b> Description: </b> <%= @task.description %>
</div>

<%= link_to 'Edit', edit_project_task_path(@project, @task), :class => 'btn' %>
<%= link_to 'Destroy', project_task_path(@project, @task), :confirm => 'Are you sure?',
  :method => :delete, :class => 'btn btn-danger' %>

<h2> Task Progress </h2>

<% unless @task.has_wip? %>
  <h3> You have been working a total of... </h3> <%= @task.time_spent %> </h2>
  <%= form_for [@project, @task, @task.work_intervals.build] do |f| %>
    <%= f.submit 'Start Working!', :class => 'btn btn-success btn-large' %>
  <% end %>
<% else %>
  <%= form_for [@project, @task, @work_interval] do |f| %>
    <%= f.submit 'Stop Working!', :class => 'btn btn-danger btn-large' %>
  <% end %>
<% end %>